# Silence macOS bash deprecation warning
export BASH_SILENCE_DEPRECATION_WARNING=1

# Set XDG Base Directory
export XDG_CONFIG_HOME=$HOME/.config

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Shell Prompt
PS1='\[\033[0;36m\]\w \[\033[38;5;208m\]→\[\033[0m\] '

# Add .local/bin to $PATH for Claude Code
export PATH="$HOME/.local/bin:$PATH"
